# ------------------------------------------------------------
# Travis configuration for CentralReport
# https://github.com/CentralReport/CentralReport
# ------------------------------------------------------------

# General declarations

language: python
python:
  - "2.6"
  - "2.7"

# Test definitions

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install build-essential"
  - "curl -sL https://deb.nodesource.com/setup | sudo bash -"
  - 'echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config' # https://github.com/travis-ci/travis-ci/issues/1588
  - "sudo apt-get install nodejs"
before_script:
  - "sudo ./build_dependencies.sh -a"
script:
  - "sudo ./tests/run_tests.sh -p -s"
after_failure:
  - "cat /tmp/centralreport_error.log"
  - "cat /tmp/centralreport_install.log"
