--- 
after_failure: 
  - "cat /tmp/centralreport_error.log"
after_script: 
  - "service centralreport status"
branches: 
  only: feature-travis-in-readme
language: python
python: 
  - "2.6"
  - "2.7"
script: install.sh
