--- 
after_failure: 
  - "cat /tmp/centralreport_error.log"
  - "cat /tmp/centralreport_install.log"
branches: 
  only: feature-travis-in-readme
language: python
python: 
  - "2.6"
  - "2.7"
script: ./travis.sh
