# ------------------------------------------------------------
# Travis configuration for CentralReport
# https://github.com/CentralReport/CentralReport
# ------------------------------------------------------------

# General declarations

language: python
python:
  - "2.6"
  - "2.7"

# Test definitions

before_install:
  - "git clone https://github.com/joyent/node.git && cd node && git checkout v0.10.32 && ./configure && make && sudo make install"
before_script:
  - "sudo ./build_dependencies.sh -a"
script:
  - "sudo ./tests/run_tests.sh -p -s"
after_failure:
  - "cat /tmp/centralreport_error.log"
  - "cat /tmp/centralreport_install.log"
