# ------------------------------------------------------------
# Travis configuration for CentralReport
# https://github.com/CentralReport/CentralReport
# ------------------------------------------------------------

# General declarations

language: python
python:
  - "2.6"
  - "2.7"

# Test definitions

script:
  - "sudo ./tests/run_tests.sh -p -s"
after_failure:
  - "cat /tmp/centralreport_error.log"
  - "cat /tmp/centralreport_install.log"
