#!/bin/bash

### BEGIN INIT INFO
# Provides:          CentralReport
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start CentralReport at boot time
# Description:       Enable service provided by CentralReport Daemon.
### END INIT INFO

case $1 in
    start | stop | restart | status)
        /usr/local/bin/centralreport $*
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
    ;;
esac

exit 0
